/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

/**
 *
 * @author MAC
 */
import java.awt.event.ActionEvent;  
import java.awt.event.ActionListener;  
import java.awt.*;  
import javax.swing.*;  
  
public class Demo extends JFrame {    
    private int delay;  
    private  int count;  
    private JButton jbt = new JButton();  
      
    public Demo(){  
        JPanel panel = new JPanel();  
        int delay = 1000; //milliseconds  
                panel.add(jbt);  
            Timer timer = new Timer(delay, new TimerListener());       
                timer.start();  
                this.add(panel);  
    }  
    private class TimerListener implements ActionListener{  
  
        @Override  
        public void actionPerformed(ActionEvent e) {  
            count++;  
            jbt.setText(""+count);  
            jbt.repaint();  
              
        }  
          
    }  
      
      
    public static void main(String[] args) {    
        Demo mydemo = new Demo();  
        mydemo.setTitle("MyDemo");  
        mydemo.setSize(200, 200);  
        mydemo.setLocationRelativeTo(null);  
        mydemo.setVisible(true);  
        mydemo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
       
    }    
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
